language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm i
script:
  - npm run build
  - npm run test
  - npm run webpack
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master
